project:
  type: website
  output-dir: docs

execute:
    freeze: auto

website:
  title: "Truth Effect Database (TED)"
  navbar:
    background: primary
    right:
      - href: contribute.qmd
        text: Contribute
      - href: get-started.qmd
        text: Get Started
      - href: explore.qmd
        text: Explore
      # - href: people.qmd
      #   text: People
      - href: publications.qmd
        text: Publications
      # - href: resources.qmd
      #   text: Resources
      - href: contact.qmd
        text: Contact
  page-footer: "Copyright 2025 &copy; Sven Lesche"
  google-analytics: ""
  site-url: https://slesche.github.io/ted-site/
  repo-url: https://github.com/SLesche/ted-site

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    include-in-header:
    - text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
