project:
  type: website
  output-dir: docs

execute:
    freeze: auto

website:
  title: "Truth Effect Database (TED)"
  navbar:
    background: primary
    right:
      - href: contribute.qmd
        text: Contribute
      - href: get-started.qmd
        text: Get Started
      # - href: news.qmd
      #   text: News
      - href: people.qmd
        text: People
      - href: publications.qmd
        text: Publications
      - href: resources.qmd
        text: Resources
      - href: contact.qmd
        text: Contact
  page-footer: "Copyright 2025 &copy; Sven Lesche"
  google-analytics: ""
  site-url: https://github.com/SLesche/ted-site
  repo-url: https://github.com/SLesche/ted-site

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
